edition = "2021"
unstable_features = true

imports_granularity="Crate"
imports_indent="Block"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 80
use_field_init_shorthand = true
use_try_shorthand = true
