[package]
name = "munote"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = "4.1"
lazy_static = "1.4.0"
munote-derive = { path = "derive" }
nom = "7.1"
nom_locate = "4.1"
parse-display = "0.8.0"
regex = "1.7"
strum = { version = "0.24", features = ["derive"] }
