[package]
name = "munote-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
eframe = "0.21"
egui = { version = "0.21", features = ["tracing"] }
midir = "0.9"
munote = { path = "../munote" }
tracing = "0.1"
tracing-subscriber = "0.3"
