[package]
name = "munote-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.21.3"
egui = { version = "0.21.0", features = ["tracing"] }
munote = { path = "../munote" }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
